export var _settings = {
	NS: 'http://www.w3.org/2000/svg',
    urlData:'data.php', urlUserData: 'user_data.csv.php', 
    urlSaveData: 'server.php?action=store_user_data', urlLockWithoutAction: 'server.php?action=', 
    urlIsSynchronized: 'server.php?action=check_synchronization', urlLogout:'server.php?action=logout', 
	ganttOperation0Color:'#2f8f2f', ganttOperation0Opacity:1.0, ganttOperation100Color:'#7f7f7f', ganttOperation100Opacity:1.0,
	ganttPhaseColor:'#0f7f07f', ganttPhaseOpacity:1.0, 
	ganttCriticalColor:'#bf2f2f', ganttCompareColor:'#cfcfdf', ganttCompareOpacity:0.75, ganttFontColor:'#4f4f4f', 
	ganttOperationStrokeWidth:0, ganttMinFontSize:6, ganttMaxFontSize:14,
	ganttLinkStrokeColor:'#000000',	ganttLinkStrokeWidth:0.5, ganttLinkStrokeDashArray:null, 
	ganttLinkOpacity:0.50, ganttLinkArrowOpacity:1.0, ganttLinkArrowWidth:8, ganttLinkArrowHeight:8, 
	ganttNoSignalColorNumber: 0x2000000, ganttNoSignalColor: '#afafaf',
	timeScaleFontColor:'#4f4f4f', timeScaleFillColor:'#cfcfdf', timeScaleStrokeColor:'#afafaf', ganttBkgrColor:'#ffffff',
	timeScaleMaxFontSize:12, minRectWidthOnTimeScale:14, minDayWidthOnTimeScale:12, 
	tableHeaderFontColor:'#4f4f4f',	tableHeaderFillColor:'#cfcfdf', tableHeaderColumnSplitterColor:'#bfbfcf',
	tableHeaderBorderColor:'#cfcfdf', tableHeaderActiveBorderColor:'#8f8f9f', 
	tableContentFontColor:'#4f4f4f', tableContentFillColor:'#efefff', tableContentStrokeColor:'#4f4f4f', 
	tableHeaderColumnHMargin:1, tableColumnHMargin:1, tableColumnTextMargin:2, 
	tableMaxFontSize:14, tableMinFontSize:2, minTableColumnWidth:4, hierarchyIndent:4,	
	scrollBkgrColor:'#cfcfcf', scrollRectColor:'#afafaf', scrollSliderColor:'#8f8f8f', scrollSliderActiveColor:'#4f4f4f',
	gridColor:'#7f7f7f', gridStrokeWidth:0.25, gridStrokeDashArray:'1,2', 
	gridCurrentTimeColor:'#bf2f2f', gridCurrentTimeStrokeWidth:1.0, 
	editedColor:'#bf2f2f', ganttChartLeftMargin:8, ganttChartRightMargin:8, 
	ganttRectTopMargin:0.6, ganttRectBottomMargin:0.125, ganttRectTopMarginTitleFree:0.1, ganttRectBottomMarginTitleFree:0.3,
	ganttCompareTopMargin:0.8, ganttCompareBottomMargin:0.0, ganttCompareTopMarginTitleFree:0.6, ganttCompareBottomMarginTitleFree:0.1,
	ganttRectBracketRelHeight:0.25,	ganttRectBracketThick:5,
	scrollThick:4, scrollSlideThick:10, verticalScrollThick:3, verticalScrollSlideThick:10, scrollSliderSize:10, 
	timeScaleScrollStep:0.1, tableScrollStep:0.1, verticalSplitterInitialPosition:0.25,
	verticalSplitterWidth:1, verticalSplitterMoveWidth:10, verticalSplitterStrokeColor:'#8f8f8f', verticalSplitterBkgrColor:'#dfdfdf',
	zoomFactor:0.25, minXZoomFactor:0.5, minSecondsZoomed:43200, ganttVisibleWidthExtra:0.5, containerHPadding:0, 
	webExportLineNumberColumnName:'f_WebExportLineNumber',
	ganttSVGCursor:'zoom-in', ganttSVGCapturedCursor:'pointer', timeSVGCursor:'zoom-in',
	readableNumberOfOperations:28, minNumberOfOperationsOnScreen:10, maxNumberOfOperationsOnScreen:50
};
